Stack-Knowledge/Stack-Knowledge-front

- packages/common/src/components/TaskCard/index.stories.tsx
- packages/common/src/components/TaskCard/index.tsx
- packages/common/src/components/TaskCard/style.ts
> 문제 카드를 제작하였습니다.
+ 문제 카드를 제작하였습니다.
+ userName: string; - 출제자나 풀이자의 이름입니다.
+ taskTitle: string; - 문제의 제목입니다.
+ miledge: number; - 문제 풀이시 지급되는 마일리지입니다.
+ isShadow?: boolean; - 그림자의 여부입니다. optional
> [Common] task card

- projects/admin/src/components/Timer/index.stories.ts
- projects/admin/src/components/Timer/index.tsx
- projects/admin/src/components/Timer/style.ts
> 타이머를 제작했습니다.
+ admin의 타이머를 제작했습니다.
client의 타이머와 admin의 타이머는 스타일이 동일합니다.
하지만 client는 시간을 표시하는 기능이고 admin은 시간을 조정하는 기능이므로 따로 제작하는게 좋을것이라 판단 했습니다.
디자인상 콜론이 동그라미 모양이지만 타이머의 콜론은 네모 모양입니다. 
추후 따로 branch를 파서 전역 font style 업데이트 하겠습니다.
> [Admin] timer

- projects/admin/src/components/ShopItemCard/style.ts
> Card 사이즈의 부적합함을 해결했습니다.
추가적으로 필요 없는 속성을 제거했습니다.
> [Admin] Update shop item card

- packages/common/src/PageContainer/index.ts
- packages/common/src/index.ts
- projects/admin/src/app/auth/login/page.tsx
> 로그인 페이지를 링킹했습니다.
> 로그인 페이지를 링킹했습니다.
> Add login path

- projects/admin/package.json
- projects/admin/tsconfig.json
> 절대경로 설정을 업데이트 했습니다.
+ tsconfig workspace admin에 추가
+ tsconfig 수정
> [All] Update absolute path

- packages/common/src/components/SubmitInput/index.stories.ts
- packages/common/src/components/SubmitInput/index.tsx
- packages/common/src/components/SubmitInput/style.ts
> Common에서 사용되는submitInput을 제작하였습니다.
> submitInput을 제작하였습니다.
> common - component에서 제작하였습니다.
> components 안에 제출하기 버튼까지 포함시켜서 제작하였습니다.
issue는 아니지만 text-area 안에 들어가는 font-size를 한번 확인하고 수정하는 것도 좋아보이는 사항입니다!
> [Common] submitInput

- packages/common/src/PageContainer/MainPage/index.stories.tsx
- packages/common/src/PageContainer/MainPage/index.tsx
- packages/common/src/PageContainer/MainPage/style.ts
- packages/common/src/PageContainer/index.ts
- packages/common/src/components/MainContents/index.stories.tsx
- packages/common/src/components/MainContents/index.tsx
- packages/common/src/components/MainContents/style.ts
- packages/common/src/components/RankingCard/index.tsx
- packages/common/src/components/RankingCard/style.ts
- packages/common/src/components/TaskCard/style.ts
- packages/common/src/components/index.ts
- packages/types/src/index.ts
- packages/types/src/mission.ts
- projects/admin/next.config.js
- projects/admin/src/app/page.tsx
- projects/client/src/app/page.module.css
> 메인 페이지를 조립 했습니다.
+ mission type을 추가했습니다.
+ MainContent 컴포넌트를 추가했습니다.
+ 더미데이터를 추가하여 각 콘텐츠를 mapping했습니다.
결과물 -> http://localhost:3000/ root 경로에서 테스트 가능합니다.
+ 추후에 API 연동 후 더미 데이터 삭제 하겠습니다.
> [Common] main page

- packages/common/src/components/Header/index.tsx
- packages/common/src/components/Header/style.ts
> Header의 style을 수정하였습니다.
+ height 90px -> 80px 디자인 반영
+ 동적 레이아웃
+ path 지정
> [Common] Update hedaer

- projects/client/src/PageContainer/ShopPage/index.tsx
- projects/client/src/PageContainer/ShopPage/style.ts
- projects/client/src/assets/index.ts
- projects/client/src/assets/svg/MinusIcon.tsx
- projects/client/src/assets/svg/PlusIcon.tsx
- projects/client/src/assets/svg/XIcon.tsx
- projects/client/src/components/ShopModal/index.stories.ts
- projects/client/src/components/ShopModal/index.tsx
- projects/client/src/components/ShopModal/style.ts
- projects/client/src/components/ShopModalItem/index.stories.ts
- projects/client/src/components/ShopModalItem/index.tsx
- projects/client/src/components/ShopModalItem/style.ts
- projects/client/src/components/index.ts
> 상점 모달을 제작 했습니다.
+ 상점 모달 제작
+ 모달 내 아이템 컨포넌트 제작
> [Client] shop modal

- packages/common/src/components/MissionDetailInput /index.tsx
- projects/admin/src/PageContainer/CreatePage/style.ts
- projects/client/src/PageContainer/MissionDetailPage/index.stories.tsx
- projects/client/src/PageContainer/MissionDetailPage/index.tsx
- projects/client/src/PageContainer/MissionDetailPage/style.ts
- projects/client/src/PageContainer/index.ts
- projects/client/src/app/mission/page.tsx
- projects/client/src/components/MissionDetailModal/index.stories.tsx
- projects/client/src/components/MissionDetailModal/index.tsx
- projects/client/src/components/MissionDetailModal/style.ts
- projects/client/src/components/Timer/index.stories.tsx
- projects/client/src/components/Timer/index.tsx
- projects/client/src/components/Timer/style.ts
- projects/client/src/components/index.ts
> Client Timer와 Client의 문제 제출 페이지를 제작하였습니다.
+ Client의 props로 hour과 minute를 받습니다.
> [Client] mission detail page

- packages/common/src/components/MissionDetailInput /index.tsx
- projects/admin/src/PageContainer/CreatePage/index.tsx
- projects/client/src/PageContainer/MissionDetailPage/index.tsx
- projects/client/src/PageContainer/MissionDetailPage/style.ts
- projects/client/src/components/MissionDetailModal/index.tsx
- projects/client/src/components/MissionDetailModal/style.ts
> Client의 미션디테일 모달 작성
> 관련된 issue -> 없다면 삭제
> [Client] mission detail modal

- projects/client/src/PageContainer/RankingPage/index.stories.tsx
- projects/client/src/PageContainer/RankingPage/index.tsx
- projects/client/src/PageContainer/RankingPage/style.ts
- projects/client/src/PageContainer/index.ts
- projects/client/src/app/ranking/page.tsx
- projects/client/src/components/index.ts
> rankingPage 제작을 하였습니다.
+ 랭킹별로 나타내고 뒤에 마일리지 포인트는 slice로 3단위 별로 , 적용하였습니다.
> [Client] ranking page

- packages/api/common/src/hooks/auth/usePostLoginCode.ts
- packages/api/common/src/hooks/index.ts
- packages/api/common/src/hooks/mission/useGetMissionList.ts
- packages/api/common/src/hooks/student/index.ts
- packages/api/common/src/hooks/student/useGetRankingList.ts
- packages/api/common/src/libs/queryKeys.ts
- packages/api/common/src/libs/urlController.ts
- packages/common/src/PageContainer/LoginPage/index.tsx
- packages/common/src/components/MainContents/index.tsx
- packages/common/src/components/MainContents/style.ts
- packages/common/src/components/RankingCard/index.tsx
> 메인 페이지의 API 연동을 완료했습니다.
+ useGetRankingList hook 제작했습니다.
+ 로그인 후 리다이렉트 구현 했습니다.
+ 데이터 값들 잘 불러와집니다!
> [Common] main page API

- packages/api/admin/index.ts
- packages/api/admin/src/hooks/index.ts
- packages/api/admin/src/hooks/mission/index.ts
- packages/api/admin/src/hooks/mission/usePostMission.ts
- packages/api/admin/src/index.ts
- packages/api/common/src/hooks/mission/useGetMissionList.ts
- packages/api/common/src/libs/queryKeys.ts
- packages/api/common/src/libs/urlController.ts
- packages/common/src/components/MissionDetailInput /index.tsx
- projects/admin/src/PageContainer/CreatePage/index.tsx
- projects/admin/src/components/Timer/index.tsx
- projects/admin/src/components/TitleInput/index.tsx
> 문제 제작 API를 연동했습니다.
+ usePostMission hook 제작
+ api/admin 세팅
+ 기존 input들 제대로 데이터값 수정 가능하도록 업데이트
정상적으로 submit되는지 확인 해주세요
아래와 같은 flow로 테스트 해주세요
-> auth/login에서 로그인
-> mission/create 이동
-> 문제 작성, 메인 리다이렉트가 문제 없이 되나요?
> [Admin] create mission

- packages/types/src/grading.ts
- packages/types/src/index.ts
- projects/admin/src/PageContainer/GradingPage/index.stories.tsx
- projects/admin/src/PageContainer/GradingPage/index.tsx
- projects/admin/src/PageContainer/GradingPage/style.ts
- projects/admin/src/PageContainer/index.ts
- projects/admin/src/app/grading/page.tsx
- projects/admin/src/components/GradingCotainer/index.tsx
- projects/admin/src/components/index.ts
> admin 문제 채점페이지 제작하였습니다.
> + 문제 채점에서 정답과 오답의 type을 boolean을 사용하여서 클릭 시 변경되게끔 하였습니다.
> [Admin] feature/gradingPage

- packages/common/src/components/TaskCard/style.ts
> [Common] missionCard side gap

- packages/api/admin/src/hooks/mission/usePostMission.ts
- packages/api/admin/src/hooks/user/useGetScoringList.ts
- packages/api/admin/src/hooks/user/usePostScoringResult.ts
- packages/api/common/src/hooks/auth/index.ts
- packages/api/common/src/hooks/auth/patchAccessToken.ts
- packages/api/common/src/hooks/auth/usePatchAccessToken.ts
- packages/api/common/src/hooks/mission/useGetMissionList.ts
- packages/api/common/src/hooks/student/useGetRankingList.ts
- packages/api/common/src/libs/api/getHeaders.ts
- packages/api/common/src/libs/api/index.ts
- packages/api/common/src/libs/api/instance.ts
- packages/types/src/tokenResponseType.ts
- pnpm-lock.yaml
- projects/client/next.config.js
- projects/client/package.json
- projects/client/src/PageContainer/MissionListPage/index.tsx
- projects/client/src/components/MissionCarousel/index.stories.tsx
- projects/client/src/components/MissionCarousel/index.tsx
- projects/client/src/components/MissionCarousel/style.ts
- projects/client/src/components/index.ts
- projects/client/tsconfig.json
> 미션 리스트 캐러셀을 제작했습니다.
+ client workspace에서 api 연동에 필요한 세팅 하였습니다.
+ 미션 리스트 캐러셀의 로직을 구현하였습니다.
로직에 대한 궁금증이 있으면 질문 해주세요~~
> [Client] mission carousel

- packages/common/src/PageContainer/LoginPage/index.tsx
> 로그인 요청 성공 후 리다이렉트 되도록 수정 했습니다.
> [Common] interceptor

- packages/api/admin/src/hooks/user/index.ts
- packages/api/admin/src/hooks/user/useGetSolveDetail.ts
- packages/api/admin/src/hooks/user/usePostScoringResult.ts
- packages/api/common/src/libs/queryKeys.ts
- packages/api/common/src/libs/urlController.ts
- projects/admin/src/PageContainer/GradingPage/index.tsx
- projects/admin/src/components/GradingCotainer/index.tsx
- projects/admin/src/components/MissionCarousel/index.tsx
> [Admin] scoring API

- packages/api/admin/src/hooks/mission/usePostMission.ts
- packages/api/client/index.ts
- packages/api/client/src/hooks/index.ts
- packages/api/client/src/hooks/solve/index.ts
- packages/api/client/src/hooks/solve/usePostSolve.ts
- packages/api/client/src/index.ts
- packages/api/common/src/hooks/mission/index.ts
- packages/api/common/src/hooks/mission/useGetMissionDetail.ts
- packages/api/common/src/libs/queryKeys.ts
- packages/api/common/src/libs/urlController.ts
- packages/common/src/components/Banner/style.ts
- packages/common/src/components/Header/index.tsx
- packages/common/src/components/Header/style.ts
- packages/common/src/components/MainContents/index.tsx
- packages/common/src/components/MissionDetailInput /index.tsx
- packages/types/src/index.ts
- packages/types/src/missionDetail.ts
- projects/admin/src/PageContainer/CreatePage/index.tsx
- projects/admin/src/components/GradingCotainer/index.tsx
- projects/admin/src/components/Timer/index.tsx
- projects/client/src/PageContainer/MissionDetailPage/index.tsx
- projects/client/src/PageContainer/MissionDetailPage/style.ts
- projects/client/src/app/mission/resolve/[missionId]/page.tsx
- projects/client/src/app/mission/resolve/page.tsx
- projects/client/src/app/ranking/page.tsx
- projects/client/src/components/MissionDetailModal/index.tsx
- projects/client/src/components/RankingHeader/style.ts
- projects/client/src/components/Timer/index.tsx
> missionList에서 상세 정보 API 연동하였습니다.
> +  url missionId에 endPoint 설정하였습니다.
+ 새로고침으로 사용한 window 객체 beforeunload 이벤트는 보안상의 문제로 새로고침 버튼을 클릭하면 
강제적으로 홈으로 이동이 애초에 불가능하게 코드가 작성이 되어 있습니다. 이 부분에 대해서 조금 .. 다시 생각을 해봐야 할 것 같습니다 ..
> [Client] client missionSolve

- package.json
- pnpm-lock.yaml
- projects/admin/src/PageContainer/CreatePage/index.tsx
- projects/admin/src/PageContainer/GradingPage/index.tsx
- projects/admin/src/app/providers.tsx
- projects/admin/src/components/ShopItemCard/index.tsx
- projects/client/src/app/providers.tsx
- projects/client/src/components/ShopModal/index.tsx
> toast 설정을 했습니다
toast 문구는 상의 후 정해보도록 합시다.
현재 디자이너께 디자인 관련해서 여쭤봤는데 답이 나오면 새로 브랜치 파서 수정하도록 하겠습니다.
현재 디자인대로 진행하겠습니다!
> [Common] toast

- packages/common/src/components/MissionDetailInput /index.stories.ts
- packages/common/src/components/MissionDetailInput /index.tsx
- projects/admin/next.config.js
- projects/admin/src/components/GradingCotainer/index.stories.tsx
- projects/client/src/components/Timer/index.stories.tsx
> 각 workspace의 build error를 해결합니다.
> BuildError

- packages/common/src/PageContainer/LoginPage/index.tsx
- projects/admin/next.config.js
- projects/client/next.config.js
> [hotfix] Image 

- packages/common/src/PageContainer/MainPage/index.tsx
- packages/common/src/components/MainContents/index.tsx
- projects/admin/src/app/page.tsx
- projects/client/src/app/page.tsx
> [hotfix] role

- packages/api/client/src/hooks/student/usePostUploadProfile.ts
- projects/client/src/components/RankingHeader/index.tsx
> [hotfix] image exception handling

- packages/types/src/studentType.ts
- projects/client/src/PageContainer/ShopPage/index.tsx
> 현재 데이터를 업데이트 했습니다.
> 상점 페이지에는 현재 포인트가 표시됩니다.
> [hotfix] currentData

- packages/api/admin/src/hooks/user/useGetScoringList.ts
- packages/api/common/src/libs/urlController.ts
- packages/common/src/PageContainer/MainPage/index.tsx
- packages/common/src/components/Banner/Banner2/index.tsx
- packages/common/src/components/MissionDetailInput /index.tsx
- packages/common/src/components/RankingCard/index.tsx
- packages/common/src/components/RankingCard/style.ts
- projects/admin/src/components/MissionCarousel/index.tsx
- projects/admin/src/components/ShopCarousel/index.tsx
- projects/client/src/components/MissionCarousel/index.tsx
> 채점하기 페이지의 리스트업 방식을 수정했습니다.
+ 채점하기 페이지의 리스트업 방식을 수정했습니다.
+ 각 캐러셀의 예외처리를 강화했습니다.
+ 이미지 출력 방식을 통일했습니다.
+ 맞춤법을 수정했습니다.
> [hotfix] scoring

- packages/common/src/components/Header/index.tsx
- packages/common/src/components/Header/style.ts
- projects/admin/src/PageContainer/GradingPage/style.ts
> Header 부분에서 menu hover시에 primary로 color 설정, path이동시에 color 설정, 채점하기 부분 채점 확인 container 수정
+ >  헤더 부분에서 stroke, fill 부분을 구분하기 위해서 따로 div 사용하여서 관리하였습니다.
> [Admin, Common] QA

- packages/common/src/components/Header/index.tsx
- packages/common/src/components/Header/style.ts
> [Common] Fix Header Active

- packages/common/src/PageContainer/LoginPage/index.tsx
> Login redirect url 부분을 env로 관리합니다.
> 작업 내용 작성.
env 업데이트 되었습니다.
> [Common] login redirect

- packages/common/src/PageContainer/LoginPage/index.tsx
- packages/common/src/PageContainer/MainPage/style.ts
- packages/common/src/components/Banner/Banner1/style.ts
- packages/common/src/components/Banner/Banner2/style.ts
- packages/common/src/components/Banner/Banner3/style.ts
- packages/common/src/components/Banner/index.tsx
- packages/common/src/components/Banner/style.ts
- packages/tsconfig/base.json
- projects/admin/next.config.js
- projects/admin/tsconfig.json
- projects/client/next.config.js
- projects/client/tsconfig.json
> 배너 반응형 작업했습니다.
+ 로그인 후 재 로그인 불가능하게 수정했습니다.
+ 개발 모드 해제했습니다.
`/` 에서 확인 가능합니다.
+ full
+ 1280 under
+ 600 under
> [Common] Responsive Banner

- packages/common/src/components/Header/index.tsx
> 문제 풀이 당시에 다른 menu와 뒤로가기를 막아주는 redirect를 onClick으로 설정하였습니다.
> 문제를 풀고 있는 상황에서는 다른 곳으로 이동이 불가능하며 새로고침시 문제 답변이 제출이 됩니다.
> [Common] Header redirect error conflict

- projects/client/src/PageContainer/MissionDetailPage/index.tsx
> 문제 풀이 예외처리를 강화했습니다.
시간이 다 되어서 문제를 제출하는데 input칸이 비어있으면 오류가 발생합니다.
비어있을 때에 예외처리를 추가해서 해결되었습니다.
> [QA] exception handling

- projects/client/src/PageContainer/MissionDetailPage/index.tsx
> client에서 문제 풀이 초기 화면에서 alert로 경고를 알려줍니다.
> [Client] solving alert

- packages/common/src/assets/Login/BottomIcon.tsx
- packages/common/src/assets/Login/TopIcon.tsx
- packages/common/src/components/Header/index.tsx
> 처음 로그인 면 svg unit을 px에서 rem으로 수정하였습니다.
> svg unit change.
> svg로 반응형을 작업을 하는데에 다소 어려움이 있어 svg의 unit만 변경하여서 반응형 작업을 하였습니다.
> [Common] Responsive login

- projects/client/src/app/layout.tsx
- projects/client/src/app/mission/list/page.tsx
- projects/client/src/app/mission/resolve/[missionId]/page.tsx
- projects/client/src/app/ranking/page.tsx
- projects/client/src/app/shop/page.tsx
> [Common] Update domain

- package.json
- pnpm-lock.yaml
- projects/client/src/app/layout.tsx
- projects/client/src/libs/gtag.ts
- projects/client/tsconfig.json
> GoogleAnalytics 세팅을 했습니다.
> + env에 NEXT_PUBLIC_GA_ID를 추가하였습니다.
> + [lib/gtag.ts](https://github.com/themoment-team/official-gsm-front/compare/feature/googleAnalytics?expand=1#diff-fc039be413ef49f8a6980c36ab6de06eb3ce4262acd589398dfeb0078f18b76d)를 생성하였습니다.
> + layout에 Script를 설정하였습니다.
> [Client] googleAnalytics

- packages/common/src/components/Header/index.tsx
> Client에 header redirect 문제 생기는 부분을 수정하였습니다.
> Header redirect tjfwjd
> [Hotfix] HeaderRedirct Error Conflict 

- projects/admin/src/PageContainer/ShopPage/index.tsx
> [hotfix] Update shop exception

- packages/api/client/src/hooks/solve/usePostSolve.ts
- packages/common/src/components/Header/index.tsx
- packages/common/src/components/Header/style.ts
- packages/common/src/components/RankingCard/style.ts
- packages/common/src/components/TaskCard/index.tsx
- packages/common/src/components/TaskCard/style.ts
- projects/client/src/PageContainer/MissionDetailPage/index.tsx
- projects/client/src/PageContainer/MissionDetailPage/style.ts
> TaskCard와 Title의 height, width 설정하였습니다. + 추가로 word break 설정하였습니다.
> res.status 판단으로 이미 푼 문제, 악용을 하여서 문제를 푼 학생 판별하는 logic 작성 하였습니다.
> + 추가적으로 마일리지 위치 position 변경이 있습니다.
> [Hotfix] TaskCard | Title Style Change | TimeError | Header Active 

- packages/common/src/styles/GlobalStyle.tsx
> 반응형을 보완합니다.
- full
- 1600 언더
- 1300 언더
- 1000 언더
- 850 언더
- 750 언더
까지 적용 됩니다.
세부적인 부분만 바꿔주세요
> [Common] Add global media query

- packages/common/src/assets/svg/DefaultProfile.svg
- packages/common/src/components/MainContents/index.tsx
- packages/common/src/components/MainContents/style.ts
- packages/common/src/components/RankingCard/style.ts
> TaskCard, MissionList 반응형 작업 제작하였습니다.
> userProfile 반응형 추가하였습니다. 
> 문제 mssionText에 responsive를 위한 container 제작을 추가하였습니다.
> [Common] TaskCard | MissionList Responsive

- projects/client/src/assets/svg/CheckBoxIcon.tsx
- projects/client/src/assets/svg/CheckedBoxIcon.tsx
- projects/client/src/assets/svg/MinusIcon.tsx
- projects/client/src/assets/svg/PlusIcon.tsx
- projects/client/src/assets/svg/XIcon.tsx
- projects/client/src/components/ShopModal/style.ts
> 상점 모달의 반응형 작업을 했습니다.
- before
- after
> [Client] Add shop modal responsive

- packages/common/src/components/Banner/style.ts
> 배너 반응형을 고쳤습니다.
- before
- after
> [Common] Update banner responsive

- packages/common/src/assets/svg/VectorIcon.tsx
- packages/common/src/hooks/index.ts
- packages/common/src/hooks/useWindowResizeEffect.ts
- packages/common/src/index.ts
- packages/common/src/stores/useWidthStore.ts
- projects/client/src/PageContainer/MissionListPage/index.tsx
- projects/client/src/PageContainer/MissionListPage/style.ts
- projects/client/src/components/MissionCarousel/index.tsx
- projects/client/src/components/MissionCarousel/style.ts
> missionCarousel 반응형 작업 제작하였습니다.
> 화면의 width에 따라서 지정하였습니다.
> + 1920 이하 852 이상
> + 853 미만 610 이상
> + 525 미만 610 이상
> + 281 미만 525 이상
> + else
> 추가 사항으로 좀 어색한 부분 있으면 말씀을 해주시기 바랍니다.
> [Client] missionCarousel Responsive

- packages/common/src/components/MainContents/style.ts
- projects/client/src/PageContainer/MissionListPage/style.ts
- projects/client/src/components/MissionCarousel/index.tsx
- projects/client/src/components/MissionCarousel/style.ts
> carousel의 반응형을 업데이트 했습니다.
carousel의 반응형을 업데이트 했습니다.
> [Hotfix] Update responsive

- packages/api/admin/src/hooks/user/usePatchApprovalStatus.ts
- projects/admin/src/components/ModalItem/index.tsx
> approved Status Type 중에 REJECT를 REJECTED로 변경하였습니다.
> [Hotfix] Fix ApprovalStatus Type

- packages/api/admin/src/hooks/user/useGetSolveDetail.ts
- packages/api/client/src/hooks/solve/usePostSolve.ts
- projects/admin/src/PageContainer/GradingPage/index.tsx
- projects/client/src/PageContainer/MissionDetailPage/index.tsx
변경된 서버 측 명세에 따라 필드 이름을 업데이트 했습니다.
> [Hotfix] Update field name

- package.json
- packages/api/admin/src/hooks/user/useGetSolveDetail.ts
- pnpm-lock.yaml
- projects/admin/package.json
- projects/admin/src/PageContainer/GradingPage/index.tsx
- projects/admin/src/PageContainer/GradingPage/style.ts
- projects/admin/src/components/GradingCotainer/index.tsx
- projects/admin/src/components/GradingCotainer/style.ts
> AI 채점 기능을 추가했습니다.
패키지 추가
- ldrs:spinner
- openai:ai
aiScoring 함수 제작
https://github.com/Stack-Knowledge/Stack-Knowledge-front/assets/106712562/5bb9461b-cfc9-46b9-8644-8dd6665acc9d
변경된 환경변수 디코에 공지하겠습니다.
> [Admin] Add scoring AI
